function B = B_linearized(l1,l2,m1,m2,th2)
%B_LINEARIZED
%    B = B_LINEARIZED(L1,L2,M1,M2,TH2)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Aug-2018 11:28:57

t2 = l1.^2;
t3 = cos(th2);
t4 = l2.*m1.*t2.*4.0;
t5 = l2.*m2.*t2.*2.0;
t6 = t3.^2;
t7 = t4+t5-l2.*m2.*t2.*t6;
t8 = 1.0./t7;
t9 = l2.^2;
t10 = m2.^2;
t11 = t2.*t9.*t10.*2.0;
t12 = m1.*m2.*t2.*t9.*4.0;
t13 = t11+t12-t2.*t6.*t9.*t10;
t14 = 1.0./t13;
t15 = m2.*t9.*2.0;
B = reshape([0.0,l2.*t8.*2.0,0.0,-t14.*(t15+l1.*l2.*m2.*t3),0.0,-t8.*(l2.*2.0+l1.*t3),0.0,t14.*(t15+m1.*t2.*2.0+m2.*t2+l1.*l2.*m2.*t3.*2.0)],[4,2]);
