function out1 = DoublePendulum_Dynamics(Q1,Q2,b1,b2,g,l1,l2,m1,m2,th1,th2,th1_d,th2_d)
%DOUBLEPENDULUM_DYNAMICS
%    OUT1 = DOUBLEPENDULUM_DYNAMICS(Q1,Q2,B1,B2,G,L1,L2,M1,M2,TH1,TH2,TH1_D,TH2_D)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    15-Aug-2018 11:28:56

t2 = l1.^2;
t3 = cos(th2);
t4 = l2.^2;
t5 = sin(th2);
t6 = sin(th1);
t7 = th1_d.^2;
t8 = m2.^2;
t9 = t3.^2;
t10 = th2_d.^2;
t11 = th1+th2;
t12 = sin(t11);
out1 = [(Q1.*l2.*2.0-Q2.*l2.*2.0-Q2.*l1.*t3-b1.*l2.*th1_d.*2.0+b2.*l2.*th2_d.*2.0+b2.*l1.*t3.*th2_d-g.*l1.*l2.*m1.*t6.*2.0-g.*l1.*l2.*m2.*t6.*2.0+l1.*m2.*t4.*t5.*t7.*2.0+l1.*m2.*t4.*t5.*t10.*2.0+l2.*m2.*t2.*t3.*t5.*t7+l1.*m2.*t4.*t5.*th1_d.*th2_d.*4.0+g.*l1.*l2.*m2.*t3.*t12)./(l2.*m1.*t2.*4.0+l2.*m2.*t2.*2.0-l2.*m2.*t2.*t9),-(Q2.*m1.*t2.*-2.0-Q2.*m2.*t2+Q1.*m2.*t4.*2.0-Q2.*m2.*t4.*2.0+b2.*m1.*t2.*th2_d.*2.0-b1.*m2.*t4.*th1_d.*2.0+b2.*m2.*t2.*th2_d+b2.*m2.*t4.*th2_d.*2.0+Q1.*l1.*l2.*m2.*t3-Q2.*l1.*l2.*m2.*t3.*2.0-g.*l1.*t4.*t6.*t8.*2.0+g.*l2.*t2.*t8.*t12-g.*l2.*t2.*t3.*t6.*t8+g.*l1.*t3.*t4.*t8.*t12+l1.*l2.*t2.*t5.*t7.*t8+l1.*l2.*t4.*t5.*t7.*t8.*2.0+l1.*l2.*t4.*t5.*t8.*t10.*2.0+t2.*t3.*t4.*t5.*t7.*t8.*2.0+t2.*t3.*t4.*t5.*t8.*t10-b1.*l1.*l2.*m2.*t3.*th1_d+b2.*l1.*l2.*m2.*t3.*th2_d.*2.0-g.*l1.*m1.*m2.*t4.*t6.*2.0+g.*l2.*m1.*m2.*t2.*t12.*2.0-g.*l2.*m1.*m2.*t2.*t3.*t6+l1.*l2.*m1.*m2.*t2.*t5.*t7.*2.0+l1.*l2.*t4.*t5.*t8.*th1_d.*th2_d.*4.0+t2.*t3.*t4.*t5.*t8.*th1_d.*th2_d.*2.0)./(t2.*t4.*t8.*2.0+m1.*m2.*t2.*t4.*4.0-t2.*t4.*t8.*t9)];
