CXX = g++
CC = g++

random_number_test: clobber make_random_number_test
	./random_number_test

make_random_number_test: random_number_test.cpp
	$(CXX) random_number_test.cpp -o random_number_test


clobber:
	rm -f random_number_test

