CXX = g++ -std=c++17
CC = g++

random_number_test: clobber random_number_test.cpp
	$(CXX) random_number_test.cpp -o random_number_test.out
	./random_number_test.out

clobber:
	rm -f random_number_test.out

