#include <random>
#include <iostream>

const float MIN_DISTRIBUTION_VALUE = 1.0;
const float MAX_DISTRIBUTION_VALUE = 2.0;

int main()
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_real_distribution<> dis(MIN_DISTRIBUTION_VALUE, MAX_DISTRIBUTION_VALUE);
    for (int n = 0; n < 100; ++n) {
        // Use dis to transform the random unsigned int generated by gen into a 
        // double in [1, 2). Each call to dis(gen) generates a new random double
        std::cout << dis(gen) << ' ';
    }
    std::cout << '\n';
}